from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from datetime import datetime, timezone

from app.database import get_db
from app.models.session import TriageSession
from app.schemas.summary import VisitSummary
from app.services.zone_flows import get_flow

router = APIRouter(prefix="/api/summary", tags=["Summary"])

_ZONE_LABELS = {
    "head": "Head", "neck": "Neck / Throat", "chest": "Chest",
    "upper_abdomen": "Upper Abdomen", "lower_abdomen": "Lower Abdomen",
    "r_arm": "Right Arm", "l_arm": "Left Arm",
    "r_forearm": "Right Forearm", "l_forearm": "Left Forearm",
    "r_hand": "Right Hand", "l_hand": "Left Hand",
    "r_thigh": "Right Thigh", "l_thigh": "Left Thigh",
    "r_leg": "Right Leg / Knee", "l_leg": "Left Leg / Knee",
    "general": "General / Whole Body",
}

_DISCLAIMER = (
    "This summary is generated by a triage guidance tool and does not constitute a "
    "medical diagnosis or medical record. Always consult a licensed healthcare provider."
)


@router.get("/{session_id}", response_model=VisitSummary)
async def get_summary(session_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(TriageSession).where(TriageSession.id == session_id))
    session: TriageSession | None = result.scalar_one_or_none()
    if not session:
        raise HTTPException(status_code=404, detail="Session not found.")

    zone_label = _ZONE_LABELS.get(session.zone_id, session.zone_id.replace("_", " ").title())
    conditions = session.possible_conditions_json or []
    main_complaint = conditions[0] if conditions else "Symptoms requiring evaluation"
    treatment = session.treatment_text or ""

    symptom_path = _build_symptom_path(session.zone_id, session.answers_json or [])
    red_flags = _extract_red_flags(session.zone_id, session.answers_json or [])
    ts = session.created_at.strftime("%B %d, %Y at %I:%M %p UTC")

    plain = _build_plain_text(
        session_id=session_id,
        zone_label=zone_label,
        main_complaint=main_complaint,
        symptom_path=symptom_path,
        red_flags=red_flags,
        conditions=conditions,
        treatment=treatment,
        triage_label=session.triage_label,
        triage_level=session.triage_level,
        ts=ts,
    )

    return VisitSummary(
        session_id=session_id,
        generated_at=datetime.now(timezone.utc).isoformat(),
        body_area=zone_label,
        main_complaint=main_complaint,
        symptom_path=symptom_path,
        red_flags_detected=red_flags,
        possible_conditions=conditions,
        treatment_recommendation=treatment,
        triage_level=session.triage_level,
        triage_label=session.triage_label,
        timestamp=ts,
        plain_text=plain,
        disclaimer=_DISCLAIMER,
    )


def _build_symptom_path(zone_id: str, answers: list[dict]) -> list[str]:
    flow = get_flow(zone_id)
    lines = []
    node_id = "start"
    for ans in answers:
        node = flow.get(node_id)
        if not node:
            break
        val = ans.get("answer_value", "")
        for opt in node.options:
            if opt.value == val:
                lines.append(f"{node.question} → {opt.label}")
                if opt.next_node is None:
                    return lines
                node_id = opt.next_node
                break
    return lines


def _extract_red_flags(zone_id: str, answers: list[dict]) -> list[str]:
    flow = get_flow(zone_id)
    flags = []
    node_id = "start"
    for ans in answers:
        node = flow.get(node_id)
        if not node:
            break
        val = ans.get("answer_value", "")
        for opt in node.options:
            if opt.value == val:
                if opt.red_flag:
                    flags.append(opt.label)
                if opt.next_node is None:
                    return flags
                node_id = opt.next_node
                break
    return flags


def _build_plain_text(
    session_id, zone_label, main_complaint, symptom_path,
    red_flags, conditions, treatment, triage_label, triage_level, ts,
) -> str:
    tier_symbols = ["🟢", "🔵", "🟡", "🔴", "🚨"]
    symbol = tier_symbols[min(triage_level, 4)]
    sep = "─" * 44

    lines = [
        "TRIAGE.AI — VISIT SUMMARY",
        sep,
        f"Date / Time:    {ts}",
        f"Body Area:      {zone_label}",
        f"Main Complaint: {main_complaint}",
        "",
        "Symptom Path:",
    ]
    for step in symptom_path:
        lines.append(f"  • {step}")
    if not symptom_path:
        lines.append("  (no path recorded)")

    if red_flags:
        lines += ["", "⚠ Red Flags Detected:"]
        for rf in red_flags:
            lines.append(f"  ⚠ {rf}")

    lines += [
        "",
        "Possible Conditions:",
    ]
    for c in conditions:
        lines.append(f"  • {c}")

    if treatment:
        lines += ["", "Treatment / Next Steps:", f"  {treatment}"]

    lines += [
        "",
        sep,
        f"{symbol} Triage Recommendation: {triage_label.upper()}",
        sep,
        "",
        f"Session ID: {session_id}",
        "",
        _DISCLAIMER,
    ]
    return "\n".join(lines)
